# ==============
# = Data Source
# ==============
spring:
  datasource:
    url: jdbc:h2:mem:hamburgueria;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;
    platform: h2
    username: hamburgueria
    password: hamburgueria
    driverClassName: org.h2.Driver

# ==================
# = Jpa / Hibernate
# ==================
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update

# ==============
# = H2 settings
# ==============
  h2:
    console:
      enabled: true
      path: /console
      settings:
        trace: false
        web-allow-others: false

# ===================
# = Logging Settings
# ===================
logging:
    level:
      root: INFO
      web: ERROR
      org.hibernate: INFO